name: Build Maven Library

on:
  push:
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@4c663ecc4a471dc6a2b382c0e49f59171c3ec632 # v1.35.3
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      node-version: '22'
      build-goals: 'clean install'
      slack-channel: '#rettighet-ci'
      short-lived: ''
